site_name: 'Kovenant'
site_url: 'http://kovenant.komponents.nl'
site_description: 'Kovenant. Promises for Kotlin.'
site_author: 'Mark Platvoet'
copyright: '2015'

repo_url: https://github.com/mplatvoet/kovenant
repo_name: 'GitHub'

pages:
- ['index.md', 'Home']
- ['api/core_usage.md', 'API Documentation', 'Core Usage']
- ['api/core_config.md', 'API Documentation', 'Core Configuration']
- ['api/combine_usage.md', 'API Documentation', 'Combine']
- ['api/functional_usage.md', 'API Documentation', 'Functional']
- ['api/jvm_usage.md', 'API Documentation', 'Executors (JVM)']
- ['android/features.md', 'Android','Features']
- ['android/config.md', 'Android','Configuring']
- ['addons/ui.md', 'Add-ons','UI']
- ['addons/disruptor.md', 'Add-ons','Disruptor']
- ['addons/progress.md', 'Add-ons','Progress']
- ['misc/goals.md', 'Misc', 'Goals']
- ['misc/performance.md', 'Misc', 'Performance']
- ['misc/considerations.md','Misc', 'Considerations']
- ['changelog.md', 'Changelog', 'Released']
- ['roadmap.md', 'Changelog', 'Roadmap']

#theme: bootstrap
theme_dir: theme/yeti